python merging_chunks.py chr1_All-dbs.csv &
python merging_chunks.py chr2_All-dbs.csv &
python merging_chunks.py chr3_All-dbs.csv &
python merging_chunks.py chr4_All-dbs.csv &
python merging_chunks.py chr5_All-dbs.csv &
python merging_chunks.py chr6_All-dbs.csv &
python merging_chunks.py chr7_All-dbs.csv &
python merging_chunks.py chr8_All-dbs.csv &
python merging_chunks.py chr9_All-dbs.csv &
python merging_chunks.py chr10_All-dbs.csv &
python merging_chunks.py chr11_All-dbs.csv &
python merging_chunks.py chr12_All-dbs.csv &
python merging_chunks.py chr13_All-dbs.csv &
python merging_chunks.py chr14_All-dbs.csv &
python merging_chunks.py chr15_All-dbs.csv &
python merging_chunks.py chr16_All-dbs.csv &
python merging_chunks.py chr17_All-dbs.csv &
python merging_chunks.py chr18_All-dbs.csv &
python merging_chunks.py chr19_All-dbs.csv &
python merging_chunks.py chr20_All-dbs.csv &
python merging_chunks.py chr22_All-dbs.csv &
python merging_chunks.py chrX_All-dbs.csv &
python merging_chunks.py chrY_All-dbs.csv &